# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      

    - name: Creating virtual env 
      run: | 
        python3 -m venv venv
        source venv/bin/activate
      
    - name: Install requirements
      run: pip install -r requirements.txt
      
    - name: Set python path requirements
      run: export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}
    
    - name: Create elastic network
      run: docker network create elastic-search
      
    - name: Run elastic and wait sometime
      run:  |
        docker run --rm -d --name elastic-search --net elastic-search -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.6.1
        sleep 15
        
    - name: Run tests with coverage
      run: coverage run -m unittest discover './test' '*_test.py'
      
    - name: Show coverage report
      run: coverage report --include **/product/*.py  --fail-under 90  

